# Generated by Django 5.2.12 on 2026-03-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriAuthentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('driver', 'Driver'), ('admin', 'Admin')], default='buyer', max_length=10),
        ),
    ]
