# Generated by Django 5.2.12 on 2026-03-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriAuthentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='weekly_schedule',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('tractor', 'Tractor'), ('pickup', 'Pickup Van'), ('mini_truck', 'Mini Truck')], max_length=20),
        ),
    ]
