# Generated by Django 5.2.12 on 2026-04-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriAuthentication', '0006_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
    ]
