# Generated by Django 5.2.12 on 2026-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriAuthentication', '0007_sellerprofile_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_profiles/'),
        ),
    ]
