# Generated by Django 5.2.12 on 2026-03-12 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agriAuthentication', '0005_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(help_text='Starting point or field location', max_length=255)),
                ('dropoff_location', models.CharField(blank=True, help_text='Destination (leave blank for stationary tractor work)', max_length=255, null=True)),
                ('job_date', models.DateTimeField(help_text='When is the service needed?')),
                ('job_description', models.TextField(help_text="Details (e.g., 'Transport 50 sacks of rice' or 'Plow 2 acres of land')")),
                ('agreed_price', models.DecimalField(decimal_places=2, help_text="Price agreed upon based on the driver's rate", max_digits=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected by Driver'), ('completed', 'Completed'), ('cancelled_driver', 'Cancelled by Driver'), ('cancelled_buyer', 'Cancelled by Buyer')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_orders', to='agriAuthentication.driverprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
