# Generated by Django 5.2.12 on 2026-05-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverorder',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled_by_buyer', 'Cancelled by Buyer'), ('cancelled_by_driver', 'Cancelled by Driver')], default='requested', max_length=20),
        ),
    ]
