# Generated by Django 5.2.12 on 2026-05-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='call_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('file', 'File'), ('audio_note', 'Audio Note'), ('audio_call', 'Audio Call Log'), ('video_call', 'Video Call Log')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, help_text="Text content or call status description (e.g., 'Missed Call')", null=True),
        ),
    ]
