# Generated by Django 5.2.12 on 2026-05-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_attachment_message_call_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio_note', 'Audio Note'), ('audio_call', 'Audio Call Log'), ('video_call', 'Video Call Log')], default='text', max_length=20),
        ),
    ]
