# Generated by Django 5.2.12 on 2026-03-11 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriAuthentication', '0005_otp'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total price at time of purchase', max_digits=10)),
                ('delivery_location', models.TextField(help_text='Where the product is being delivered')),
                ('payment_type', models.CharField(choices=[('cash', 'Cash on Delivery'), ('online', 'Online Payment')], max_length=10)),
                ('status', models.CharField(choices=[('order_placed', 'Order Placed'), ('preparing_shipment', 'Preparing Shipment'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up by Courier'), ('sorting_facility', 'At Sorting Facility'), ('departed_sorting', 'Departed Sorting Facility'), ('delivery_hub', 'Arrived at Delivery Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='order_placed', max_length=30)),
                ('cancel_reason', models.TextField(blank=True, help_text='Reason for cancelling the order', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_orders', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='agriAuthentication.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
