# Generated by Django 5.2.12 on 2026-04-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_favoriteproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(blank=True, help_text="Estimated delivery time (e.g., '30-50 minutes')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(blank=True, help_text="Delivery type (e.g., 'Home Delivery', 'Pickup','Free Delivery')", max_length=100, null=True),
        ),
    ]
