# Generated by Django 5.2.12 on 2026-04-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_delivery_time_product_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark as popular product'),
        ),
    ]
