# Generated by Django 5.2.12 on 2026-04-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Weight in the specified unit', max_digits=10),
            preserve_default=False,
        ),
    ]
