# Generated by Django 5.2.12 on 2026-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_cost',
            field=models.IntegerField(default=0, help_text='Delivery cost (e.g., in BDT or your local currency)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(blank=True, choices=[('20-30_min', '20-30 minutes'), ('30-60_min', '30-60 minutes'), ('60-90_min', '60-90 minutes'), ('2-4_hours', '2-4 hours'), ('today_day', 'Today Day Delivery'), ('next_day', 'Next Day Delivery'), ('next_month', 'Next Month Delivery')], help_text='Estimated delivery time', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('home_delivery', 'Home Delivery'), ('pickup', 'Pickup'), ('free_delivery', 'Free Delivery')], help_text='Delivery type', max_length=50, null=True),
        ),
    ]
