# Generated by Django 5.2.12 on 2026-05-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_order_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_placed', 'Order Placed'), ('preparing_shipment', 'Preparing Shipment'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up by Courier'), ('sorting_facility', 'At Sorting Facility'), ('departed_sorting', 'Departed Sorting Facility'), ('delivery_hub', 'Arrived at Delivery Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='products.order')),
            ],
        ),
    ]
